title: ACIT2620 Networking Notes
repository: yveshema/networking
author: Yves Rene Shema
theme: minima
markdown: GFM
plugins:
  - jekyll-relative-links
  - jekyll-gfm-admonitions
  - jekyll-timeago
relative_links:
  enabled: true
  collection: true
exclude:
  - docs
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/