# Actions workflow for generating slides using marp
name: CI

# trigger on push events on main
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Ensure build directory exists
              run: mkdir -p build

            - name: Copy static files
              run: cp -R _config.yml README.md pages build/

            - name: Copy images directory (if exists)
              run: if [[ -d img ]]; then cp -R img build/img; fi

            - name: Marp Build (docs folder, html)
              uses: docker://marpteam/marp-cli:v3.0.2
              with:
                args: --theme ./themes/graph_paper.css -I docs/ -o build/slides/
              env:
                MARP_USER: root:root

            - name: Marp Build (docs folder, pdf)
              uses: docker://marpteam/marp-cli:v3.0.2
              with:
                args: --theme ./themes/graph_paper.css  --pdf --allow-local-files -I docs/ -o build/download/
              env:
                MARP_USER: root:root

            - name: Deploy production
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: gh-pages
                folder: ./build/

            